spring.application.name: mini-banking-system

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_bank_db
    username: postgres
    password: said1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

