create table customers
(
    id         integer generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    first_name varchar(255),
    last_name  varchar(255),
    email      varchar(255),
    phone      varchar(255)
);

create table accounts
(
    id             integer generated by default as identity primary key,
    created_at     timestamp(6) not null,
    updated_at     timestamp(6),
    account_number varchar(255) not null unique,
    account_type   varchar(20),
    status         varchar(20),
    balance        numeric(38, 2),
    currency       varchar(10),
    customer_id    integer references customers (id)

);


create table transactions
(
    id                     integer generated by default as identity primary key,
    created_at             timestamp(6)   not null,
    updated_at             timestamp(6),
    reference              varchar(100)   not null unique,
    type                   varchar(20)    not null,
    status                 varchar(20)    not null,
    amount                 numeric(15, 2) not null,
    description            varchar(255),
    source_account_id      integer references accounts (id),
    destination_account_id integer references accounts (id),

    constraint chk_transactions_type
        check (type in ('DEPOSIT', 'WITHDRAW', 'TRANSFER')),

    constraint chk_transactions_status
        check (status in ('SUCCESS', 'FAILED', 'REJECTED')),

    constraint chk_transactions_amount_positive
        check (amount > 0)

);


